# see http://conda.pydata.org/docs/travis.html

language: python
sudo: false   # use container based build
notifications:
  email: false
branches:
  only:
    - master

matrix:
  fast_finish: True
  include:
    - python: 3.5
      env: CONDA_ENV=py35
    - python: 3.6
      env: CONDA_ENV=py36
    - python: 3.7
      env: CONDA_ENV=py37
    - python: 3.6
      env: CONDA_ENV=py36-xarray-dev
    - python: 3.6
      env: CONDA_ENV=py36-attrs-dev
    - python: 3.5
      env: CONDA_ENV=docs
  allow_failures:
    - python: 3.6
      env: CONDA_ENV=py36-xarray-dev
    - python: 3.6
      env: CONDA_ENV=py36-attrs-dev

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a

install:
  - if [[ "$CONDA_ENV" == "docs" ]]; then
      conda env create -n test_env --file doc/environment.yml;
    else
      conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml;
    fi
  - source activate test_env
  - conda list
  - pip install --no-deps -e .

script:
  - python -OO -c "import xsimlab"
  - if [[ "$CONDA_ENV" == "docs" ]]; then
      conda install -c conda-forge sphinx_rtd_theme;
      cd doc;
      sphinx-build -n -j auto -b html -d _build/doctrees . _build/html;
    elif [[ "$CONDA_ENV" == *"dev" ]]; then
      pytest xsimlab --verbose;
    else
      pytest xsimlab --cov=xsimlab --cov-report term-missing --verbose;
    fi

after_success:
  - if [[ "$CONDA_ENV" != *"dev" ]]; then
      coveralls
    fi
