name: xarray-simlab-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19.1.0
  - python=3.7
  - numpy=1.16.0
  - pandas=0.23.3
  - xarray=0.13.0
  - ipython=7.8.0
  - matplotlib=3.0.2
  - graphviz
  - python-graphviz
  - nbconvert=5.6.0
  - sphinx=1.8.5
  - nbsphinx=0.4.2
  - pandoc=2.7.3
