name: xarray-simlab-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs
  - python=3.5
  - numpy=1.12
  - pandas=0.22
  - xarray=0.10.0
  - ipython=6.2.1
  - ipykernel=4.6.1
  - matplotlib=2.0.2
  - graphviz
  - python-graphviz
  - nbconvert=5.2.1
  - sphinx=1.6.2
  - nbsphinx=0.3.1
  - pandoc=1.19.2
